{% set name = "kite" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpdcj/KITE/archive/refs/tags/{{ version }}.tar.gz
  sha256: 56b7944512b0b25d9d6c1be6481db83abe1e47e2dc6d8cbc509a514bb26534c9

build:
  noarch: generic
  number: 0

requirements:
  build:
    - openjdk =21
    - sed          # [not win]
    - m2-sed       # [win]
  run:
    - openjdk >=17

test:
  commands:
    - kite

about:
  home: https://github.com/hpdcj/KITE
  summary: "KITE: K-mer Index Tversky Estimator application"
  description: |
    KITE is a Java application that detects pathogens within samples.
    It can be used for DNA and/or RNA FASTQ files.
    KITE stands for K-mer Index Tversky Estimator, as the application leverages
    k-mer analysis combined with the Tversky index.
    KITE not only expedites viral detection but also maintains comparable
    sensitivity to existing approaches.
  license: BSD-3-Clause
  license_file: 
    - LICENSE
    - build/reports/dependency-license/ 


extra:
  recipe-maintainers:
    - faramir
